linker:
    resource: "@LinkerBundle/Controller/"
    type:     annotation
    prefix:   /

book_web:
    resource: "@BookWebBundle/Controller/"
    type:     annotation
    prefix:   /

dodatki_kategorie:
    resource: "@DodatkiKategorieBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
